version: '3'
services:
  mysql-db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - pet-network

  petclinic:
    image: rozen88/spring-petclinic-data-jdbc
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/petclinic?autoReconnect=true&useSSL=false
    ports:
      - 8080:8080
    networks:
      - pet-network

networks:
  pet-network:
    driver: bridge
